modLoader = "javafml"
loaderVersion = "${loaderVersionRange}"
license = "MIT"
issueTrackerURL="https://github.com/TonimatasDEV/LoggerFixer/issues"

[[mods]]
modId = "loggerfixer"
version = "${modVersion}"
displayName = "Logger Fixer"
updateJSONURL="https://api.modrinth.com/updates/logger.fixer/forge_updates.json"
displayURL="https://github.com/TonimatasDEV/LoggerFixer"
credits="TonimatasDEV - Developer"
authors = "TonimatasDEV"

description = '''
Why we need these logs?
'''

[[mixins]]
config = "loggerfixer.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.loggerfixer]]
modId = "neoforge"
type = "required"
versionRange = "${neoVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.loggerfixer]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"

#[features.recipefixer]
#openGLVersion="[3.2,)"
